name: GitHub Actions
on:
  - push
  - workflow_dispatch
env:
  APP_IMAGE: "oauth-v2-php-client"
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.2', '8.3' ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker container
        run: |
          docker compose build dev --build-arg PHP_VERSION=${{ matrix.php-version }}

      - name: Install dependencies & Run tests
        run: |
          if [ "${{ matrix.php-version }}" = "8.2" ]; then
            docker compose run dev bash -c "composer update --prefer-lowest && composer ci"
          else
            docker compose run dev bash -c "composer update && composer ci"
          fi
