name: GitHub Actions
on: [ push ]
env:
  APP_IMAGE: "oauth-v2-php-client"
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image and run tests
        run: |
          docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
          docker-compose run ci
