name: GitHub Actions
on:
  - push
  - workflow_dispatch
env:
  APP_IMAGE: "oauth-v2-php-client"
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build Docker container
        run: docker compose build dev

      - name: Install dependencies & Run tests
        run: docker compose run dev bash -c "composer update && composer ci"
